name: Convert Subscription

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Run subconverter
        run: |
          docker run --rm -v "${{ github.workspace }}:/subconverter" tindy2013/subconverter:latest /bin/bash -c "wget -qO- http://dbpngo.xyz/xlvpn | ./subconverter" > converted.yaml
          
      - name: Commit and push if changes
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Actions'
          git add .
          git commit -m 'Convert subscription' -a || exit 0 # 只在有更改时提交
          git push
